steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/langflow:${_IMAGE_TAG}',
      '-t', 'gcr.io/$PROJECT_ID/langflow:latest',
      '.'
    ]

  # Etapa 2: Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: [
      'push', 'gcr.io/$PROJECT_ID/langflow:${_IMAGE_TAG}'
    ]

  # Etapa 3: Deploy automático no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Deploying image gcr.io/$PROJECT_ID/langflow:${_IMAGE_TAG} to Cloud Run..."
        gcloud run deploy ${_SERVICE} \
          --image gcr.io/$PROJECT_ID/langflow:${_IMAGE_TAG} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --port ${_PORT} \
          --memory ${_MEMORY} \
          --timeout 900

images:
  - 'gcr.io/$PROJECT_ID/langflow:${_IMAGE_TAG}'

substitutions:
  _IMAGE_TAG: 'latest'
  _SERVICE: 'langflow'
  _REGION: 'southamerica-east1'
  _PORT: '7860'
  _MEMORY: '2Gi'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '2400s'
